server:
  port: 8080
spring:
  application:
    name: kafka-stream-concept
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: kafka-stream-concept
      properties:
        num:
          stream:
            threads: 2
        topology:
          optimization: all
    producer:
      properties:
        linger:
          ms: 100
    consumer:
      auto-offset-reset: latest
topics:
  play-odd-or-even-topic: kafka-stream-concept.odd-or-even.play.v1.dev
  odd-topic: kafka-stream-concept.odd.number.v1.dev
  even-topic: kafka-stream-concept.even.number.v1.dev
